name: PR CI

on:
  pull_request:
    branches: [ "kt-rewrite" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Give permission to executable
        run: chmod +x gradlew

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Curbox API unit tests
        run: |
          ./gradlew testFullDebugUnitTest \
            --tests neth.iecal.curbox.api.UsageDataApiTest \
            --tests neth.iecal.curbox.api.WebsiteUsageApiTest \
            --tests neth.iecal.curbox.data.db.WebsiteHourlyUsageCodecTest

      - name: Build Fdroid Debug APK
        run: ./gradlew assembleFdroidDebug

      - name: Upload Fdroid Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: fdroid-debug-apk
          path: app/build/outputs/apk/fdroid/debug
